### ISSUE TITLE
How to use new action

### ISSUE THREAD

**Issue by Fudal** [shorebirdtech/shorebird-release#2]
I just want to know how can I replace my current action:
```
- name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build Android App Bundle
        run:  shorebird release android -- --dart-define=SENTRY_DSN=${{secrets.SENTRY_DSN}}
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
```

with new action:

```
- name: 🚀 Shorebird Release
  id: shorebird-release
  uses: shorebirdtech/shorebird-release@v0
```

So I don't know where can I pass my release arguments.

**Comment by felangel** [comment]
Hi @Fudal 👋 
You can now pass additional `args` like:

```yaml
env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

- name: 🐦 Setup Shorebird
   uses: shorebirdtech/setup-shorebird@v0
     with:
       flutter-version: ${{ env.FLUTTER_VERSION }}

- name: 🚀 Shorebird Release
  id: shorebird-release
  uses: shorebirdtech/shorebird-release@v0
  with:
    args: "-- --dart-define=SENTRY_DSN=${{secrets.SENTRY_DSN}}"
  ```
  
  Hope that helps 👍
