### ISSUE TITLE
Process completed with exit code 70

### ISSUE THREAD

**Issue by ssorrychoi** [shorebirdtech/shorebird-release#4]
```
       - name: 🐦 Setup Shorebird
          uses: shorebirdtech/setup-shorebird@v0
          with: 
            flutter-version: 3.16.5

        - name: Use Shorebird 
          run: shorebird --version
                
        - name: 🚀 Shorebird Release
          uses: shorebirdtech/shorebird-release@v0
          id: shorebird-release
          with:
            platform: android
            working-directory: ./path/to/app
```

I want to deploy android application using Github Actions. So I used upper code, but that code return the error.

`Error: Process completed with exit code 70. `

It's not working. Anybody help me in this error?
